99cats/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats  #, only: [:index]
  resources :cat_rental_requests do
    patch '/approve' => 'cat_rental_requests#approve'
    patch '/deny' => 'cat_rental_requests#deny'
  end
  resource :session, only: [:create, :new, :destroy]
  resource :user, only: [:create, :new]
end

99cats/app/models/user.rb
class User < ActiveRecord::Base
  
  after_initialize :set_session_token!
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true  
  
  has_many(
    :cats,
    class_name: "Cat",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :logins,
    class_name: "Login",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
    )
  
  def self.find_by_credentials(user_name, password)
    return nil if password.empty?
    return nil unless User.find_by_username(user_name)
    user = self.find_by_username(user_name)
    user.is_password?(password) ? user : nil
  end
  
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end
  
  def set_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    self.save!
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
 
 
end

99cats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login
  
  
  def create
    @user = User.new(user_params)
    @user.password = user_params[:password_digest]
    if @user.save
      login_user!
    else
      flash[:notice] = @user.errors.full_messages
      render :new
    end
  end
  
  def new
    @user = User.new
    render :new
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password_digest)
  end
  
  def check_login
    redirect_to cats_url if current_user
  end
  
end

99cats/app/views/users/new.html.erb
<h1>Create a new account!</h1>
<form action="<%= user_url%>" method="POST">
    <input 
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
  
    <label for="user_username">Username:</label>
    <input 
      type="text" 
      name="user[username]" 
      id="user_username" 
      value="<%= @user.username %>">
    <br>
      
    <label for="user_password">Password:</label>
    <input 
      type="password" 
      name="user[password_digest]" 
      id="user_password">
    <br>
      
    <input type="submit" value="Get Yours!">
</form>