RedditClone/config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
  resources :comments
  
end

RedditClone/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author_id, :post_id, presence: true
  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id
  )
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
end

RedditClone/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )
  
  has_many(
    :postsubs,
    class_name: "Postsub",
    foreign_key: :sub_id,
    primary_key: :id
  )
  
  has_many(
    :subs,
    through: :postsubs,
    source: :sub
  )
  
  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id,
    dependent: :destroy
  )
end

RedditClone/app/models/postsub.rb
class Postsub < ActiveRecord::Base
  validates :post_id, :sub_id, presence: true
  
  belongs_to(
    :post,
    class_name: "Post",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  belongs_to(
    :sub,
    class_name: "Sub",
    foreign_key: :sub_id,
    primary_key: :id
  )
  
  def self.add_subs_from_new_posts(subs, post_id)
    subs.each do |sub_id|
      Postsub.create!(sub_id: sub_id.to_i, post_id: post_id.to_i)
    end
  end
end

RedditClone/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :postsubs,
    class_name: "Postsub",
    foreign_key: :sub_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :posts,
    through: :postsubs,
    source: :post
  )
end

RedditClone/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  
  after_initialize :ensure_session_token
  
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { 
    minimum: 6, 
  }
  
  has_many(
    :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many(
    :posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  has_many(
    :comments,
    class_name: "Comment",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user && user.is_password?(password) ? user : nil
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def login!(user)
    session[:session_token] = user.session_token
  end
  
  def logout!(user)
    user.session_token = user.class.generate_session_token
    session[:session_token] = nil
    nil
  end
  
  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_login
    redirect_to new_session_url unless logged_in? 
    
  end
  
  def is_a_moderator
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless @sub.moderator.id == current_user.id
  end
end

RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render :new
  end
  
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:notice] = @comment.errors.full_messages
      render :new
    end
    
  end
  
  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def show
    @post = Post.find(params[:id])
    render :show
  end
  
  def edit
    @sub = Sub.find(params[:sub_id]) unless params[:sub_id].nil?
    @post = Post.find(params[:id])
    render :edit
  end
  
  def new
    @post = Post.new
    # render :new
  end
  
  def create
    @post = Post.new(post_params)    
    @post.author_id = current_user.id
    
    if @post.save
      Postsub.add_subs_from_new_posts(params[:post][:subs], @post.id)
      redirect_to(:back)
    else
      flash.now[:notice] = @post.errors.full_messages
      render :new
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      unless params[:sub_id].empty?
        redirect_to sub_url(params[:sub_id])
      else
        redirect_to post_url(@post)
      end
    else
      flash.now[:notice] = @post.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    
    redirect_to sub_url(@post.sub)
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :content, :url)
    end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    username = params[:user][:username]
    password = params[:user][:password]
    user = User.find_by_credentials(username, password)
    
    if user.nil?
      flash.now[:notice] = "Thats not a real user!"
      render :new
    else
      login!(user)
      redirect_to user_url
    end
  end
  
  def destroy
    logout!(current_user)
    
    redirect_to new_session_url
  end
  
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  before_action :is_a_moderator, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end
  
  def show
    @subs = Sub.all
    @sub = Sub.find(params[:id])
    render :show
  end
  
  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end
  
  def new
    @sub = Sub.new
    render :new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.errors.full_messages
      render :new
    end
    
  end
  
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy!
    redirect_to user_url
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to user_url
    else
      flash.now[:notice] = @user.errors.full_messages
      render :new
    end
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
  <div style='border: 2px dotted green;'>
    <p>Jerk with an opinion: <%= comment.author.username %></p>
  
    <p><%= comment.content %></p>
    
    <% if current_user.id == comment.author.id || 
          current_user.id == @post.sub.moderator %>
    <% end %>
  </div>
<% end %>

RedditClone/app/views/comments/_form.html.erb
<h4>Comments</h4>
<form action="/comments" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input
     name="comment[post_id]"
     type="hidden"
     value="<%= @post.id %>">
   <br>
  
    
  <label for="comment_content">Content</label><br>
  <textarea name="comment[content]" id="comment_content"></textarea>
  <br>
  <input type="submit" value="Create Comment!">
    <br>  <br>
</form>
  

RedditClone/app/views/posts/_form.html.erb
<h4>Create Post</h4>
<form action="/posts" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <label for="post_title">Title</label>
  <input 
    type="text" 
    name="post[title]" 
    id="post_title"
    value="">
  <br>
  <label for="post_url">url</label>
  <input 
    type="text" 
    name="post[url]" 
    id="post_url"
    value="">
  <br>
  <% @subs.each do |sub| %>
    <input type="checkbox" 
           name="post[subs][]" 
           id="post_sub_<%=sub.title%>" 
           value = "<%=sub.id %>">
           <label for="post_sub_<%=sub.title%>"><%=sub.title%></label>
  <% end %>
  <br>
  <label for="post_content">Content</label>
  <textarea name="post[content]" id="post_content"></textarea>
  <br>
  <input type="submit" value="Create Post!">
</form>
  

RedditClone/app/views/posts/_posts.html.erb
<% @sub.posts.each do |post| %>
  <div style='border: 2px dotted red;'>
    <% unless post.url.empty? %>
      <%= link_to post.title, post.url %>
    <% else %>
      <%= post.title %>
    <% end %>
  
    <p>Post Author: <%= post.author.username %></p>
  
    <p><%= post.content %></p>
    <% if current_user.id == post.author.id || 
          current_user.id == Sub.find(params[:id]).moderator.id %>
          <%= link_to "Edit Post", edit_post_url(post, sub_id: @sub.id) %>
          <%= link_to "Delete Post", post_url(post), method: :delete %>
    <% end %>
  </div>
<% end %>

RedditClone/app/views/posts/edit.html.erb
<h4>Edit Post</h4>
<form action="<%= post_url(@post)%>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

    <input type="hidden" name="sub_id" value="<%= @sub.id unless @sub.nil? %>">
     
  <label for="post_title">Title</label>
  <input 
    type="text" 
    name="post[title]" 
    id="post_title"
    value="<%= @post.title %>">
  <br>
  <label for="post_url">url</label>
  <input 
    type="text" 
    name="post[url]" 
    id="post_url"
    value="<%= @post.url %>">
  <br>
  <label for="post_content">Content</label>
  <textarea name="post[content]" id="post_content"><%= @post.content %></textarea>
  <br>
  <input type="submit" value="Edit Post!">
</form>
  

RedditClone/app/views/posts/show.html.erb
  <% unless @post.url.empty? %>
    <%= link_to @post.title, @post.url %>
  <% else %>
    <%= @post.title %>
  <% end %>

  <p>Post Author: <%= @post.author.username %></p>

  <p><%= @post.content %></p>
  
  <% if current_user.id == @post.author.id || 
        current_user.id == @post.sub.moderator %>
        <%= link_to "Edit Post", edit_post_url(@post) %>
        <%= link_to "Delete Post", post_url(@post), method: :delete %>
  <% end %>

  <%= render partial: "comments/form" %>
  <%= render partial: "comments/comments" %>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<form action="<%= sub_url(@sub) %>" method="POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <label for="sub_title">Title</label>
  <input 
    type="text" 
    name="sub[title]" 
    id="sub_title"
    value="<%= @sub.title %>">
  <label for ="sub_description">Description</label>
  <input 
    type="text" 
    name="sub[description]" 
    id="sub_description" 
    value = "<%= @sub.description %>">  
  
  <input type="submit" value="Update Sub!">
</form>
  

RedditClone/app/views/subs/index.html.erb
<h1>All Subs</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><%= link_to sub.title, sub_url(sub) %> - by 
        <%= sub.moderator.username %></li>
  <% end %>
</ul>

<%= link_to "Create new sub", new_sub_url %>

RedditClone/app/views/subs/new.html.erb
<h1>Create Sub</h1>
<form action="/subs" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <label for="sub_title">Title</label>
  <input 
    type="text" 
    name="sub[title]" 
    id="sub_title"
    value="<%= @sub.title %>">
  <label for ="sub_description">Description</label>
  <input 
    type="text" 
    name="sub[description]" 
    id="sub_description" 
    value = "<%= @sub.description %>">  
  
  <input type="submit" value="Create Sub!">
</form>
  

RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h2><%= @sub.description %></h2>
<h2>Moderated by: <%= @sub.moderator.username %></h2>

<%= render partial: "posts/form" %>
<%= render partial: "posts/posts" %>

<%= link_to "Back to all subs", subs_url %>

<% if current_user.id == @sub.moderator.id %>
  <%= link_to "Destroy Sub", sub_url(@sub), method: :delete %>
<% end %>

RedditClone/app/views/users/new.html.erb
<h1>Sign up!</h1>
<form action="/user" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">
     
  <label for="user_username">Username</label>
  <input 
    type="text" 
    name="user[username]" 
    id="user_username"
    value="<%= @user.username %>">
  <label for ="user_password">Password</label>
  <input 
    type="password" 
    name="user[password]" 
    id="user_password">
  <input type="submit" value="Create Account!">
</form>
  

RedditClone/app/views/users/show.html.erb
<h1><%= current_user.username%>!!</h1>

<h2>My Subs</h2>
<ul>
<% current_user.subs.each do |sub| %>
  <li><%= link_to sub.title, sub_url(sub) %></li>
<% end %>
</ul>

<%= link_to "see subs", subs_url %>